In [1]:
#here i an going to learn the consept of scaler, vector,and last but not least matriex.

In [16]:
import numpy as np

In [17]:
# Scaler
s = 5
s

5

In [28]:
# vector
v = np.array([5,-2,3])
v

array([ 5, -2,  3])

In [34]:
# Matrix
m = np.array([[5,-2,3],[1,2,3]])
m

array([[ 5, -2,  3],
       [ 1,  2,  3]])

In [36]:
# tensor
# it carry multiple matriex 
# ex
m1 = np.array([[1,2,3],[4,5,6]])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
m2 = np.array([[7,8,9],[10,11,12]])
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [38]:
t = np.array([m1,m2])
t

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
# the (.shape) show the sixe of the matrix 
# In this it will shoe (num of matix, num of row, num of col)
t.shape

(2, 2, 3)

In [41]:
# now do add in matriex
m1 + m2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [42]:
# now do subtracrion of matrix
m1-m2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [43]:
# now we have to learn how to transposing the matriex 
# only we have the write ".T" only for transposing it 
# example
m1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
# now i am learning that how to transpose the vector
# here we not directly transpose the matriex
# Example 
v1 = np.array([1,2,3,4])
v1.T
# see here is no working 

array([1, 2, 3, 4])

In [45]:
# now what we have to do is 
# do like this only 
x_reshaped = v1.reshape(1,4)
x_reshaped

array([[1, 2, 3, 4]])

In [46]:
x_reshaped.T
# there is how "Transposing work"

array([[1],
       [2],
       [3],
       [4]])

In [48]:
# now we have to do "dot ptroduct"
v2 = np.array([4,2,7,3])
v2

array([4, 2, 7, 3])

In [51]:
# now do "Dot product"
# only we have to use ".dot" use this only
print(np.dot(v1,v2))

41
