<h1>NumPy Basics</h1>

<h3><b>Instaling & Updating the Package</b></h3>

<p>
    NumPy is pre-Install while i use "<b>Anaconda</b>"</br>
    To get the latest verson <b>pip install numpy --upgrade</b>
</p>

In [5]:
import numpy as np

<h3><b>Using Numpy</b></h3>

In [6]:
array_v = np.array([1,2,3])

In [7]:
array_v

array([1, 2, 3])

<h4>Now go for 2D Array it's mean "Matriex"</h4>

In [9]:
array_m = np.array([[1,2,3],[4,5,6]])
array_m

array([[1, 2, 3],
       [4, 5, 6]])

<h2>NumPy Basics - Exercise #1</h2>

<ol>
    <li>Import the NumPy library using the conventional alias.</li>
    <li>Create a one-dimensional NumPy array containing the following values in order:
        <br> <b>4, 5, 7, 10</b></li>
    <li>Print the contents of the array.</li>
    <li>Print the type of the variable to verify that it is a<b> numpy.ndarray</b>.</li>
</ol>

In [19]:
import numpy as np

In [20]:
array_1 = np.array([4,5,7,10])

In [21]:
print(array_1)
print(type(array_1))

[ 4  5  7 10]
<class 'numpy.ndarray'>


<h2>NumPy Basics - Exercise #2</h2>

<pre>
The NumPy library has been imported using the conventional alias, 
and a one-dimensional NumPy array has been created containing the 
following values in order:
<b>4, 5, 7, 10</b>
</pre>

<ol>
    <li>Create a two-dimensional array using two lists - one with the values 4 and 5, and the other - with 7 and 10. For simplicity, call this array array_2.</li>
    <li>Print the contents of array_2.</li>
    <li> Compute and display the mean of array_1 and the overall mean of array_2</li>
    <li> Compute and display the row-wise mean of array_2.</li>
    <li> Compute and display the column-wise mean of array_2.</li>
</ol>

In [22]:
import numpy as np

In [24]:
array_2 = np.array([[4,5],[7,10]])

In [25]:
print(array_2)

[[ 4  5]
 [ 7 10]]


In [26]:
print(np.mean(array_1))
print(np.mean(array_2))

6.5
6.5


In [28]:
print(np.mean(array_2, axis = 1))

[4.5 8.5]


In [31]:
print(np.mean(array_2, axis = 0))

[5.5 7.5]
